# --------- Instrument Sounds ---------
[instruments]
name = 'Instruments'
path = 'sound/runtime/instruments/synthesis_samples'

[instruments."Muted String (Low)"]
path = 'guitar/crisis_muted/C2.ogg'

[instruments."Muted String (Medium)"]
path = 'guitar/crisis_muted/C3.ogg'

[instruments."Muted String (High)"]
path = 'guitar/crisis_muted/C4.ogg'

# [instruments."Banjo (Medium)"]
# path = 'guitar/crisis_muted/banjo/Cn3.ogg'

# --------- Misc Sounds ---------

[misc]
name = 'Miscellaneous'

[misc.Squeaky]
path = 'sound/items/toysqueak1.ogg'
max_speed = 4

[misc.Beep]
path = 'sound/machines/terminal_select.ogg'
max_pitch = 1 #Bringing the pitch higher just hurts your ears :<
max_speed = 4 #This soundbyte's too short for larger speeds to not sound awkward

[misc."Synthetic (Grunt)"]
path = 'sound/misc/bloop.ogg'

[misc."Synthetic (Normal)"]
path = 'sound/machines/uplinkerror.ogg'
max_speed = 4

[misc.Windy]
path = 'sound/weapons/bulletflyby.ogg'
max_pitch = 1.6

[misc.Brassy]
path = 'sound/machines/clockcult/integration_cog_install.ogg'

# --------- Misc Animal Sounds ---------

[animal]
name = "Animal"
path = 'monkestation/sound/voice/barks/animal'

[animal."Moth Squeak"]
path = 'mothsqueak.ogg'

[animal.Chirp]
path = 'chirp.ogg'

[animal.Caw]
path = 'caw.ogg'

[animal.chittery]
path = 'mothchitter2.ogg'

# --------- Don't Starve Sounds ---------

[dont_starve]
name = "Don't Starve"
path = 'monkestation/sound/voice/barks/dont_starve'

[dont_starve.Wilson]
path = 'wilson.ogg'

[dont_starve.woodie]
path = 'woodie.ogg'

[dont_starve.wurt]
path = 'wurt.ogg'

[dont_starve.wx78]
path = 'wx78.ogg'

# --------- Kazooie Sounds ---------
[kazooie]
name = "Kazooie"
path = 'monkestation/sound/voice/barks/kazooie'

# --------- Goonstation Sounds ---------
[goon]
name = "Goonstation"
path = 'goon\sounds\misc\talk'

[goon.Blub]
path='blub.ogg'
ask_path='blub_ask.ogg'
exclaim_path='blub_exclaim.ogg'

[goon."Bottalk 1"]
path='bottalk_1.ogg'
min_speed = 3
max_speed = 9

[goon."Bottalk 2"]
path='bottalk_2.ogg'

[goon."Bottalk 3"]
path='bottalk_3.ogg'

[goon.Buwoo]
path='buwoo.ogg'
ask_path='buwoo_ask.ogg'
exclaim_path='buwoo_exclaim.ogg'

[goon.Cow]
path='cow.ogg'
ask_path='cow_ask.ogg'
exclaim_path='cow_exclaim.ogg'

[goon.Cyborg]
path='cyborg.ogg'
ask_path='cyborg_ask.ogg'
exclaim_path='cyborg_exclaim.ogg'

[goon.Lizard]
path='lizard.ogg'
ask_path='lizard_ask.ogg'
exclaim_path='lizard_exclaim.ogg'

[goon.Pug]
path='pug.ogg'
ask_path='pug_ask.ogg'
exclaim_path='pug_exclaim.ogg'

[goon.Pugg]
path='pugg.ogg'
ask_path='pugg_ask.ogg'
exclaim_path='pugg_exclaim.ogg'

[goon.Radio]
path='radio.ogg'

[goon.Radio2]
path='radio2.ogg'

[goon."Radio Ai"]
path='radio_ai.ogg'

[goon.Roach]
path='roach.ogg'
ask_path='roach_ask.ogg'
exclaim_path='roach_exclaim.ogg'

[goon.Skelly]
path='skelly.ogg'
ask_path='skelly_ask.ogg'
exclaim_path='skelly_exclaim.ogg'

[goon."Speak 1"]
path='speak_1.ogg'
ask_path='speak_1_ask.ogg'
exclaim_path='speak_1_exclaim.ogg'

[goon."Speak 2"]
path='speak_2.ogg'
ask_path='speak_2_ask.ogg'
exclaim_path='speak_2_exclaim.ogg'

[goon."Speak 3"]
path='speak_3.ogg'
ask_path='speak_3_ask.ogg'
exclaim_path='speak_3_exclaim.ogg'

[goon."Speak 4"]
path='speak_4.ogg'
ask_path='speak_4_ask.ogg'
exclaim_path='speak_4_exclaim.ogg'
