#define RBMK_AMBIENT_TEMP 293
// Baseline subsystem timings used to keep old RBMK tuning stable while scaling with seconds_per_tick.
#define RBMK_MACHINERY_PROCESS_SECONDS 2
#define RBMK_ATMOS_PROCESS_SECONDS 0.5
#define RBMK_TEMP_CRITICAL 6500
#define RBMK_TEMP_DISPLAY_MAX 20000
#define RBMK_TEMP_STRESS_THRESHOLD 8000
#define RBMK_TEMP_DAMAGE_RAMP 9500

#define RBMK_MODIFIER_PLASMA_TEMP_LIMIT_BONUS 1250
#define RBMK_MODIFIER_PLASMA_TEMP_LIMIT_BONUS_MAX 4000
#define RBMK_MODIFIER_BLUESPACE_COOLANT_BONUS 0.20
#define RBMK_MODIFIER_BLUESPACE_COOLANT_BONUS_MAX 0.80
#define RBMK_MODIFIER_DIAMOND_FLUX_MULT_BONUS 0.12
#define RBMK_MODIFIER_DIAMOND_FLUX_MULT_BONUS_MAX 0.48

#define RBMK_TEMP_OFF RBMK_AMBIENT_TEMP
#define RBMK_TEMP_RUNNING 500
#define RBMK_TEMP_MODERATE 1500
#define RBMK_TEMP_HOT 3000
#define RBMK_TEMP_VERYHOT 4000
#define RBMK_TEMP_MAXSAFE 6000
#define RBMK_TEMP_OVERHEAT 7000
#define RBMK_TEMP_MELTDOWN 8000

#define RBMK_VC_TEMP_COEFF 0.00008
#define RBMK_VC_TEMP_COMPONENT_MAX 1.2
#define RBMK_VC_PRESSURE_COMPONENT_MAX 1
#define RBMK_VC_COOLANT_COMPONENT_MAX 0.8
#define RBMK_VC_COOLANT_MOLES_TARGET 450
#define RBMK_VC_MAX 3.0

#define RBMK_FLUX_GAIN 0.8
#define RBMK_TEMP_GAIN_PER_SECOND (0.24 / RBMK_MACHINERY_PROCESS_SECONDS)
#define RBMK_HEAT_SCALING 0.05
#define RBMK_FLUX_DECAY_PER_SECOND (0.05 / RBMK_MACHINERY_PROCESS_SECONDS)
#define RBMK_RADIATION_DECAY_PER_SECOND (0.12 / RBMK_MACHINERY_PROCESS_SECONDS)
#define RBMK_RADIATION_FLUX_MULT 0.10
#define RBMK_RADIATION_TEMP_MULT 0.00035
/// Fraction of active fuel-rod radiation that remains with the control rods fully inserted.
#define RBMK_RESIDUAL_RADIATION_MULTIPLIER 0.15

#define RBMK_MAX_INTEGRITY 100
#define RBMK_INTEGRITY_DAMAGE_CAP_PER_SECOND 0.75
#define RBMK_PRESSURE_INTEGRITY_DAMAGE_CAP_PER_SECOND 0.35
#define RBMK_INTEGRITY_COOLDOWN_DAMAGE_CAP_PER_SECOND 0.25
#define RBMK_INTEGRITY_GLOBAL_WARNING_THRESHOLD 10
#define RBMK_DAMAGE_OVERLAY_1 90
#define RBMK_DAMAGE_OVERLAY_2 70
#define RBMK_DAMAGE_OVERLAY_3 50
#define RBMK_DAMAGE_OVERLAY_4 25

#define RBMK_CONTROL_ROD_MAX 100
#define RBMK_REPAIRABLE_TEMP_LIMIT 2500
#define RBMK_WELDER_REPAIR_AMOUNT 5
#define RBMK_WELDER_REPAIR_TIME 6 SECONDS
#define RBMK_WELDER_REPAIR_FUEL_COST 1

#define RBMK_ROD_CONSOLE_SAFE_TEMP_LIMIT 2500
#define RBMK_ROD_TOOL_REMOVE_TIME_NORMAL 3 SECONDS
#define RBMK_ROD_TOOL_REMOVE_TIME_SPECIAL 6 SECONDS
#define RBMK_ROD_TOOL_REMOVE_TIME_CASCADE 15 SECONDS
#define RBMK_ROD_TOOL_HOT_KNOCKBACK_TEMP 2500
#define RBMK_ROD_TOOL_HOT_KNOCKBACK_RANGE 4
#define RBMK_ROD_TOOL_CASCADE_KNOCKBACK_RANGE 7

#define RBMK_COOLANT_VOLUME_MAX 2000
#define RBMK_INLET_RATE_MIN 0
#define RBMK_INLET_RATE_DEFAULT 75
#define RBMK_INLET_RATE_MAX 250
/// Maximum pressure rise the reactor coolant injector can overcome above its supply pressure.
#define RBMK_INLET_PUMP_HEAD 6500
#define RBMK_OUTLET_RATE_MIN 0
#define RBMK_OUTLET_RATE_DEFAULT 75
#define RBMK_OUTLET_RATE_MAX 750
/// Prevents a single atmos update from evacuating the hot core and causing a pressure rebound on the next inlet update.
#define RBMK_OUTLET_MAX_INVENTORY_FRACTION 0.5
#define RBMK_PRESSURE_WARNING 6000
#define RBMK_PRESSURE_CRITICAL 7200
#define RBMK_PRESSURE_EXTREME 8600
#define RBMK_PRESSURE_DAMAGE_DIVISOR 1200
#define RBMK_PRESSURE_CRITICAL_DAMAGE_DIVISOR 700
#define RBMK_PRESSURE_EXTREME_DAMAGE_BONUS 2

#define RBMK_CORE_HEAT_CAPACITY 450000
#define RBMK_COOLANT_EFFECTIVE_MOLES_TARGET 900
#define RBMK_COOLANT_STAGNANT_FLOW_RATIO 0.05
#define RBMK_COOLANT_ONE_PORT_FLOW_MULT 0.35
#define RBMK_COOLANT_EXCHANGE_COEFFICIENT 0.10
#define RBMK_COOLANT_EXCHANGE_FLOW_BONUS 0.50
#define RBMK_COOLANT_MAX_CORE_TEMP_CHANGE 450
#define RBMK_COOLANT_MAX_GAS_TEMP_CHANGE 1800

#define RBMK_TRITIUM_RATE 0.00075
/// Keeps tritium useful as a coolant byproduct without letting it overwhelm pressure control every process tick.
#define RBMK_TRITIUM_PRODUCTION_MULTIPLIER 20

#define RBMK_MELTDOWN_PREFIX "RBMK MELTDOWN"
#define RBMK_MELTDOWN_BROADCAST "RBMK Reactor critical failure!"
#define RBMK_MELTDOWN_RADIATION TRUE
#define RBMK_MELTDOWN_ATMOS_DUMP TRUE
#define RBMK_MELTDOWN_EXPLOSIONS TRUE
#define RBMK_MELTDOWN_ALARMS TRUE
#define RBMK_MELTDOWN_RAD_RANGE 20
#define RBMK_MELTDOWN_RAD_THRESHOLD 0.05
#define RBMK_MELTDOWN_DEV_RANGE 0
#define RBMK_MELTDOWN_HEAVY_RANGE 5
#define RBMK_MELTDOWN_LIGHT_RANGE 15
#define RBMK_MELTDOWN_FLASH_RANGE 18
#define RBMK_MELTDOWN_WARNING_DELAY 8 SECONDS
#define RBMK_MELTDOWN_EFFECT_STAGGER 1
#define RBMK_MELTDOWN_FALLOUT_DELAY 1 MINUTES
#define RBMK_MELTDOWN_FLOOR_DAMAGE_RANGE 5
#define RBMK_MELTDOWN_FLOOR_SPACE_CHANCE 45

#define RBMK_MAX_RADIATION 700
#define RBMK_MAX_FLUX 1200

#define RBMK_FLUX_ANOMALY_THRESHOLD 350
#define RBMK_FLUX_ANOMALY_HIGH 700
#define RBMK_FLUX_ANOMALY_EXTREME 1000

#define RBMK_FLUX_ANOMALY_COOLDOWN_LOW 35 SECONDS
#define RBMK_FLUX_ANOMALY_COOLDOWN_HIGH 25 SECONDS
#define RBMK_FLUX_ANOMALY_COOLDOWN_EXTREME 18 SECONDS

#define RBMK_FALLOUT_SPREAD_INTERVAL 10 SECONDS
#define RBMK_FALLOUT_RADIUS_STEP 6
#define RBMK_FALLOUT_MAX_RADIUS 255

#define RBMK_SOUND_LOW 1
#define RBMK_SOUND_HIGH 2
#define RBMK_SOUND_MAX 3

#define RBMK_ROUND2(x) (round((x), 0.01))
