#define CARGO_UNION_NAME "name"
#define CARGO_UNION_LEADER "leader"
#define CARGO_UNION_BANK "bank"

#define ANNOUNCE_START_VOTE "VOTE_STARTED"
#define ANNOUNCE_CREW "ANNOUNCE_TO_CREW"
#define ANNOUNCE_INTO_EFFECT "ANNOUNCE_INTO_EFFECT"
#define ANNOUNCE_DEADLOCK "ANNOUNCE_DEADLOCK"
#define ANNOUNCE_FAILURE "ANNOUNCE_FAILURE"
