//Bark defines
#define BARK_DEFAULT_MINPITCH 0.4
#define BARK_DEFAULT_MAXPITCH 2
#define BARK_DEFAULT_MINVARY 0.1
#define BARK_DEFAULT_MAXVARY 0.8
#define BARK_DEFAULT_MINSPEED 4
#define BARK_DEFAULT_MAXSPEED 16
